module.exports = {
  siteMetadata: {
    title: `Elszámolás 2000 Bt.`,
    description: `Az Elszámolás 2000 Bt. több éves tapasztalattal végzi precíz munkáját a könyvelés, bérszámfejtés, adóbevallás, konzultáció, mérleg készítés és könyvelési tanácsadás területén Egerben.`,
    author: `@pityubak`,
    keywords: `könyvelés, eger, könyvelőiroda, bérszámfejtés, nav ,adóbevallás`,
    siteUrl: `https://elszamolas2000bt.hu/`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-image`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /assets/, // See below to configure properly
        },
      },
    },
    `gatsby-plugin-styled-components`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-preact`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Elszámolás 2000 Bt`,
        short_name: `elszamolas2000`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `standalone`,
        icon: `src/images/logo.webp`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: "gatsby-plugin-robots-txt",
      options: {
        host: "https://elszamolas2000bt.hu",
        sitemap: "https://elszamolas2000bt.hu/sitemap.xml",
        policy: [{ userAgent: "*", allow: "/" }],
      },
    },
    `gatsby-plugin-sitemap`,
    {
      resolve: `gatsby-plugin-purgecss`,
      options: {
        printRejected: true, // Print removed selectors and processed file names
        develop: true, // Enable while using `gatsby develop`
        // tailwind: true, // Enable tailwindcss support
        // ignore: ['/ignored.css', 'prismjs/', 'docsearch.js/'], // Ignore files/folders
        // purgeOnly : ['components/', '/main.css', 'bootstrap/'], // Purge only these files/folders
        purgeCSSOptions: {
          safelist: [
            "navbar-dark",
            "fixed-top",
            "scrolling-navbar",
            "navbar",
            "navbar-expand-lg",
            "container-fluid",
            "mask",
            "rgba-black-strong",
            "flex-center",
            "card-header",
            "card-body",
            "card-text",
            "card-title",
            "navbar-toggler",
            "navbar-toggler-icon",
            "navbar-brand",
            "collapse",
            "show",
            "navbar-collapse",
            "navbar-nav",
            "ml-auto",
            "fa",
            "fa-info-circle",
            "fa-chart-pie",
            "fa-calculator",
            "fa-headphones-alt",
            "fa-briefcase",
            "fa-3x",
            "fa-at",
            "fa-university",
            "fa-credit-card",
            "row",
            "justify-content-center",
            "col",
            "border-rgba-teal-strong",
            "card",
            "list-group",
            "list-group-item",
            "list-group-item-undefined",
            "list-group-item-action",
            "card-footer",
            "col-lg-6",
            "text-info",
            "needs-validation",
            "h5",
            "text-center",
            "mb-4",
            "grey-text",
            "input-group",
            "input-group-prepend",
            "input-group-text",
            "fa-user",
            "prefix",
            "form-control",
            "fa-envelope",
            "fa-tag",
            "fa-pencil-alt",
            "btn-unique",
            "btn-outline-unique",
            "btn",
            "Ripple-parent",
            "page-footer",
            "font-small",
            "pt-4",
            "mt-4",
            "text-md-left",
            "py-3",
            "tooltip",
            "px-2",
            "Ripple ",
            "is-reppling",
            "carousel",
            "carousel-fade",
            "z-depth-1",
            "carousel-inner",
            "carousel-item",
            "active",
            "view",
            "d-block",
            "w-100",
            "fa-balance-scale",
            "fa-address-book",
            "fa-hand-holding-usd",
            "btn-default",
            "table-responsive",
            "table",
            "table-striped",
            "text-white",
            "special-color",
            "tr",
            "td",
            "th",
            "/tr$/",
            "h4",
            "a",
            "h1",
            "h2",
            "ul",
            "li",
            "button",
            "/^tr:/",
            "tbody",
            "/^collapse:/",
            "top-nav-collapse",
          ],
        },
      },
    },
  ],
}
